language: php
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
before_script:
  - "mkdir -p ~/.composer"
  - cp src/test/resources/travis-ci/travis-composer-config.json ~/.composer/config.json
  - wget https://raw.github.com/ehough/throwback/develop/src/main/bash/travis-setup.sh
  - chmod a+x travis-setup.sh
  - ./travis-setup.sh
script: "phpunit -c src/test/resources/phpunit.xml.dist"
